"""
Recovery Coach Agent Contracts.

Defines the request and response models for the Recovery Coach Agent.
The Recovery Coach produces the student-facing empathetic, constructive dialogue.
"""
from __future__ import annotations

from typing import Any
from pydantic import BaseModel, Field

from chatbot.backend.schemas.student import StudentContext
from chatbot.backend.schemas.insight import StudentInsight
from chatbot.backend.schemas.planner import StudyPlan


class CoachMessageItem(BaseModel):
    """Minimal message format used in CoachRequest conversation history."""
    role: str = Field(description="'user' | 'assistant'")
    content: str


class CoachRequest(BaseModel):
    """Input payload for Recovery Coach Agent."""
    student_id: str
    user_message: str = Field(description="Latest message from the student")
    resolved_user_message: str | None = Field(
        default=None,
        description="Unified/resolved message when current turn is a follow-up constraint",
    )
    student_context: StudentContext | None = None
    conversation_history: list[CoachMessageItem] = Field(default_factory=list)
    student_insight: StudentInsight | None = None
    study_plan: StudyPlan | None = None

    # Pre-classified response mode from the orchestrator router
    # One of: direct_factual, identity, format_constrained, educational,
    #         task_request, resource_request, academic_insight, study_plan,
    #         emotional_support, conversational
    response_mode: str | None = Field(
        default=None,
        description="Pre-classified response behavior mode from the intent router",
    )

    # Name extracted from conversation history when student_context.student_name is empty
    conversational_name: str | None = Field(
        default=None,
        description="Student's name as stated in conversation (e.g. 'my name is Ajmal')",
    )

    # Structured user facts (name, hometown, location, interests) from conversational memory
    user_facts: dict[str, Any] | None = Field(
        default=None,
        description="Known facts about the user (e.g. hometown, location, interests)",
    )

    # Parsed response constraints (one_word, one_sentence, exact_items, etc.)
    constraints: dict[str, Any] | None = Field(
        default=None,
        description="Structured format and length constraints",
    )

    # Active Teach Me session state
    teaching_state: dict[str, Any] | None = Field(
        default=None,
        description="Active tutoring/teaching state (topic, concept, question, difficulty)",
    )

    # Active Quiz session state
    quiz_state: dict[str, Any] | None = Field(
        default=None,
        description="Active quiz session state (topic, question, score, progress)",
    )

    # Supplemental learning history (quiz performance by topic, preferences)
    learning_history: dict[str, Any] | None = Field(
        default=None,
        description="Compact learning history and explicit student preferences",
    )


class CoachResponse(BaseModel):
    """
    Final student-facing response generated by the Recovery Coach.
    Always uses empowering, positive, actionable language.
    """
    response_text: str = Field(
        description="The primary natural-language conversational reply to the student",
    )
    has_study_plan: bool = Field(
        default=False,
        description="Flag indicating if a structured study plan is attached",
    )
    study_plan: StudyPlan | None = Field(
        default=None,
        description="Attached study plan object if generated",
    )
    teaching_state: dict[str, Any] | None = Field(
        default=None,
        description="Updated teaching state if currently in Teach Me mode",
    )
    quiz_state: dict[str, Any] | None = Field(
        default=None,
        description="Updated quiz state if currently in Quiz mode",
    )
    suggested_followups: list[str] = Field(
        default_factory=list,
        description="Quick prompt suggestions for the student's next question",
    )
    resources: list[str] = Field(
        default_factory=list,
        description="Optional relevant resources mentioned in the advice",
    )
    metadata: dict[str, Any] = Field(default_factory=dict)
